### ISSUE TITLE
Maya crashed when I return to the medic tool after removing wrong reference!

### ISSUE THREAD

**Issue by DangoWang** [sol-ansano-kim/medic#7]
Hi~I got a problem in maya 2020.1 with your tool. It seems that I cannot fix the problems tested by medic manually.Here are my steps:
1.Create a reference(whatever it is);
2.Open medic for checking, and it got an error in checking referenceNode;
3.Open referenceEditor, remove the reference manually;
4.Click the listView again, maya crashed (ㄒoㄒ)..
If you have any idea about this, plz tell me, thank you !!!!!!!!!!

**Comment by sol-ansano-kim** [comment]
Hi, I found the reason what make you maya crashed.
Unloading a reference node and deleting an object seems to be different.
Usually even the node is gone the Maya core doesn’t occur crash but unloading reference seems to do.
I need some time for fix this issue, so for now please select some other ui item not to show referenced nodes on node name list widget before you remove(or unload) reference and push test button for refreshing. ( Or unloading references before you use medic is best way maybe)
Sorry for inconvenience. I’ll fix this soon.

**Comment by sol-ansano-kim** [comment]
I think I had misunderstood that. Deleting is also not safe if its memory released(flushing undo chuck or new scene)
Anyway I'm going to look for a way solve this issue.

**Comment by sol-ansano-kim** [comment]
Here is medic 1.5.0, I think this will solve the problem.
https://github.com/sol-ansano-kim/medic/releases/tag/1.5.0

**Comment by DangoWang** [comment]
wawooo!!!Thank you so much for your hard work!Excellent!Take a break my bro!

**Comment by sol-ansano-kim** [comment]
Thank you for reporting, close this issues

**Comment by sol-ansano-kim** [comment]
Hi, 1.5.0 has a problem on isAlive method. fixed on 1.5.1
